FROM ubuntu:latest AS build
RUN apt-get update
RUN apt-get install openjdk-22-jdk -y

COPY . .

RUN apt-get install maven -y
RUN mvn clean install

FROM openjdk:22-slim

EXPOSE 9090
COPY --from=build /target/webservices-0.0.1-SNAPSHOT.jar webservices.jar